// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD81JpddGzcg5YxOMee5zxLy7W6JxnteRk',
    appId: '1:525596284092:web:f328ac1892b3bc7eee6cb9',
    messagingSenderId: '525596284092',
    projectId: 'closure-700ba',
    authDomain: 'closure-700ba.firebaseapp.com',
    storageBucket: 'closure-700ba.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8-t8XPycRFXQ9ylxTa50hrkom-TleQ7s',
    appId: '1:525596284092:android:c708c9da0ba601abee6cb9',
    messagingSenderId: '525596284092',
    projectId: 'closure-700ba',
    storageBucket: 'closure-700ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwG0hRveJmQOyXXpcI7hQTreBtrf4kQk4',
    appId: '1:525596284092:ios:42b939b0e5b621e8ee6cb9',
    messagingSenderId: '525596284092',
    projectId: 'closure-700ba',
    storageBucket: 'closure-700ba.appspot.com',
    androidClientId: '525596284092-c0cslfvvpddp07ut2bla3eclbvv9imr1.apps.googleusercontent.com',
    iosClientId: '525596284092-0sl5qlqafv617ad048rcd0tm40q79jis.apps.googleusercontent.com',
    iosBundleId: 'com.example.closure',
  );
}
